### ISSUE TITLE
[Bug-Chat] Generated code is not fully displayed 

### ISSUE THREAD

**Issue by BeiningYing** [getcursor/cursor#569]
When using [Chat], the generated code is not fully displayed and the code box does not make sense.
The image below：
![image](https://user-images.githubusercontent.com/118277279/236394773-decca3c9-3129-4e45-9d04-aa09a34005eb.png)

**Comment by hxshandle** [comment]
Yes I have the same issue

**Comment by danperks** [comment]
Resolved in later versions

**Comment by xjtusjtu** [comment]
Version: 0.42.3
VSCode Version: 1.93.1
Commit: 949de58bd3d85d530972cac2dffc4feb9eee1e40
Date: 2024-10-16T17:56:07.754Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

The problem still exists on the latest version 0.42.3


![image](https://github.com/user-attachments/assets/b9f90532-2fd7-427c-a829-00c652801383)
