### ISSUE TITLE
[Solved] Jupyter Notebook Support

### ISSUE THREAD

**Issue by JunityZhan** [getcursor/cursor#576]
I find out there is an installed jupyter extention on Cursor automatically, but it doesn't work. Even though I can view my .ipynb file, and I can select kernel, but I cannot run it. I suspect that it is because the version is too low. The jupyter version on Cursor is v2023.1.200, and I cannot uninstall it to install a newer version. The newest version is v2023.4.1011241018. I try to install the extention on the visual studio expension website, and I drag it into Cursor, it just can not add into it, saying that "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.76.2'."
There is no way for me to uninstall the Jupyter
![image](https://user-images.githubusercontent.com/82944614/236680712-f694ee5f-84ab-47e7-ae5c-6522bd36fbf0.png)

The error occurs like this:

```
Failed to start the Kernel. 
Failed to start the Kernel 'pytorch (Python 3.8.16)'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. this.e is not a constructor
```

![image](https://user-images.githubusercontent.com/82944614/236680575-983ea93d-5690-48f0-a578-cbc5578026d7.png)

```
info 21:32:54.368: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0acc2f101574258dfe5e6be69b236460c90050dff2fe0c82448b6891eba226c5f.c:\Users\linka\anaconda3\envs\pytorch\python.exe.c:\Users\linka\anaconda3\envs\pytorch\python.exe.-m#ipykernel_launcher (Python Path: c:\Users\linka\anaconda3\envs\pytorch, EnvType: Conda, EnvName: 'pytorch', Version: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]) for 'c:\Users\linka\.cursor-tutor\1.ipynb' (disableUI=false)
info 21:32:54.368: Checking for server existence.
info 21:32:54.368: Connecting to server
info 21:32:54.368: Launching server
warn 21:32:54.369: Error occurred while trying to start the kernel, options.disableUI=false [n [Error]: 
	at new n (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36353)
	at n.from (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36431)
	at t.Kernel.G (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4138071)

TypeError: this.e is not a constructor
	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749] {
  category: 'unknown',
  originalException: [TypeError: this.e is not a constructor
  	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
  	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
  	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
  	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749]
}
warn 21:32:54.369: Kernel Error, context = start [n [Error]: 
	at new n (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36353)
	at n.from (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36431)
	at t.Kernel.G (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4138071)

TypeError: this.e is not a constructor
	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749] {
  category: 'unknown',
  originalException: [TypeError: this.e is not a constructor
  	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
  	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
  	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
  	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749]
}
info 21:32:54.372: Process Execution: > ~\anaconda3\envs\pytorch\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\anaconda3\envs\pytorch\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 21:32:54.580: Dispose Kernel 'c:\Users\linka\.cursor-tutor\1.ipynb' associated with 'c:\Users\linka\.cursor-tutor\1.ipynb'
error 21:32:54.580: Error in execution [n [Error]: 
	at new n (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36353)
	at n.from (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36431)
	at t.Kernel.G (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4138071)

TypeError: this.e is not a constructor
	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749] {
  category: 'unknown',
  originalException: [TypeError: this.e is not a constructor
  	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
  	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
  	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
  	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749]
}
error 21:32:54.581: Error in execution (get message for cell) [n [Error]: 
	at new n (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36353)
	at n.from (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:17:36431)
	at t.Kernel.G (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4138071)

TypeError: this.e is not a constructor
	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749] {
  category: 'unknown',
  originalException: [TypeError: this.e is not a constructor
  	at l.createSystemVariables (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4650897)
  	at t.expandWorkingDir (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4042228)
  	at v.l (c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4052237)
  	at async c:\Users\linka\AppData\Local\Programs\Cursor\resources\app\extensions\vscode-jupyter\dist\extension.node.js:2:4050749]
}```

**Comment by healerlalala** [comment]
me too! How can I fix it? Have you found it out?

**Comment by flpenteado** [comment]
Me too! :(

**Comment by georgebwang** [comment]
Same here. :(

**Comment by vassagoP** [comment]
Same here!

**Comment by JasonChiu-lone** [comment]
same here :(

**Comment by JasonChiu-lone** [comment]
Here is a possible solution: 
Download official ms-jupyter from [here](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter), extract it, and find `extension.node.js`.
Replace `/Applications/Cursor.app/Contents/Resources/app/extensions/vscode-jupyter/dist/extension.node.js` with the one from microsoft.

Guessing there might be bugs in the jupyter extension from cursor marketplace.

**Comment by JunityZhan** [comment]
> Here is a possible solution: Download official ms-jupyter from [here](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter), extract it, and find `extension.node.js`. Replace `/Applications/Cursor.app/Contents/Resources/app/extensions/vscode-jupyter/dist/extension.node.js` with the one from microsoft.
> 
> Guessing there might be bugs in the jupyter extension from cursor marketplace.

It works for me! I see their AI can work on jupyter notebook. The AI know what I am writing in each blocks, but there are just some problems on running jupyter notebook. After solve it by this method, everything is good.

**Comment by greenzorro** [comment]
> Here is a possible solution: Download official ms-jupyter from [here](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter), extract it, and find `extension.node.js`. Replace `/Applications/Cursor.app/Contents/Resources/app/extensions/vscode-jupyter/dist/extension.node.js` with the one from microsoft.
> 
> Guessing there might be bugs in the jupyter extension from cursor marketplace.

Works for me! Really appreciate this.

**Comment by danperks** [comment]
I'll leave this issue pinned for people to get to easily. Any problems regarding Juypter notebooks should be reported here, as others may likely face the same issue.

**Comment by ssime-git** [comment]
it worked for me too

**Comment by codejedi-ai** [comment]
Click download extention and rename the .vsix to .zip and look for extension.node.js

**Comment by arvid220u** [comment]
This should be fixed in version 0.2.25! You should just be able to install the Jupyter extension and it should just work!

Please let me know if it doesn't, and I will re-open this issue.

**Comment by danperks** [comment]
Just pinning to avoid duplicate issues where people haven't searched for it first, done the same with SSH support, hope thats alright :)

**Comment by arvid220u** [comment]
no that's great! but in this case i think this issue is obsolete since version 0.2.25, since jupyter now works as normal (but lmk if it doesn't!)

**Comment by TeleporterGuy** [comment]
Hey. I'm running latest cursor and could not run jupyter notebook at all. Cursor suggested to install additional libraries, which i agreed, but then it remains at loading of pandas and even after 5-10 minutes does nothing.
I also could not install Jupyter notebook extension from MS store. I'll try the steps from above a bit later today.

**Comment by kylepapili** [comment]
I am still having this issue:
```
VSCode Version: 1.91.1
Commit: 2804893a83ef162ae6c48e8254717e25c7c7c510
Date: 2024-08-29T17:42:50.254Z (4 days ago)
Electron: 29.4.0
ElectronBuildId: undefined
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0
```


Tried to download, extract, and replace the extension.node.js file but I do not see any `vscode-jupyter` directory in my `/Applications/Cursor.app/Contents/Resources/app/extensions/`.  I'm not sure where cursor is looking for the vscode extension...

Any suggestions?

**Comment by deoxyribose** [comment]
@kylepapili 
I found it under `./.cursor/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js`,
try
`find -iname "extension.node.js"`

**Comment by BlakeCrowther** [comment]
Ran into this issue today. 

I did not find `ms-tools` or `vscode-jupyter` in `./.cursor/extensions/`, however, switching to the pre-release version of Jupyter within the cursor marketplace resolved the issue for me.

**Comment by carl-laplace** [comment]
I ran into a similar issue and using the pre-release version also worked for me.
